# This docker compose makes use of unofficial images
# due to confluent only offering linux/amd arch images and not multi-platform.
# As soon as official multi-platform images are out, use them here.
# More info: https://eb7team.atlassian.net/browse/AP-695

---
version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: oms-mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/saturn-db
  zookeeper:
    image: kymeric/cp-zookeeper:latest
    hostname: zookeeper
    container_name: oms-zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: kymeric/cp-kafka:latest
    hostname: broker
    container_name: oms-broker
    depends_on:
      - zookeeper
    restart: 'on-failure'
    ports:
      - '9092:9092'
      - '29092:29092'
    expose:
      - '9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  order-management-service:
    container_name: order-management-service
    image: order-management-service:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn nx serve order-management-service --host 0.0.0.0
    ports:
      - 3333:3333
    environment:
      NODE_ENV: development
      MONGO_URI: '${MONGO_URI}'
      MONGO_LOG_LEVEL: 5
      MONGO_MAX_POOL_SIZE: 20
    volumes:
      - ./apps/:/usr/src/app/apps/
      - ./libs/:/usr/src/app/libs
      - ./tools/:/usr/src/app/tools/
      - ./node_modules:/usr/src/app/node_modules
      - ./tsconfig.base.json:/usr/src/app/tsconfig.base.json
      - ./nx.json:/usr/nx.json
      - ./package.json:/usr/package.json
    depends_on:
      - mongo
  order-producer:
    container_name: order-producer
    image: order-producer:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn nx serve order-producer --host 0.0.0.0
    ports:
      - 3334:3334
    environment:
      NODE_ENV: development
      APP_PORT: 3334
    volumes:
      - ./apps/:/usr/src/app/apps/
      - ./libs/:/usr/src/app/libs
      - ./tools/:/usr/src/app/tools/
      - ./node_modules:/usr/src/app/node_modules
      - ./tsconfig.base.json:/usr/src/app/tsconfig.base.json
      - ./nx.json:/usr/nx.json
      - ./package.json:/usr/package.json
volumes:
  mongodb:
